# Generated by Django 4.2.8 on 2023-12-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'username must be unique'}, max_length=60, unique=True)),
                ('balance', models.PositiveBigIntegerField(default=0, verbose_name='Баланс в тийинах')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField(verbose_name='ID Аккаунта')),
                ('token', models.CharField(max_length=512, verbose_name='Токен')),
                ('additional_data', models.JSONField(default=dict, verbose_name='Дополнительная информация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('auto_payment', models.BooleanField(default=True, verbose_name='Авто оплата')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.PositiveIntegerField(verbose_name='ID Аккаунта')),
                ('receipt_id', models.CharField(max_length=32, unique=True, verbose_name='ID Чека')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('FAILED', 'Ошибка'), ('PAID', 'Оплачен')], verbose_name='Статус')),
                ('info', models.CharField(max_length=128, verbose_name='Инфо')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=60, verbose_name='Название на [Russian]')),
                ('description_ru', models.CharField(max_length=500, verbose_name='Описание на [Russian]')),
                ('description_list_ru', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание на [Russian]')),
                ('title_en', models.CharField(max_length=60, verbose_name='Название на [English]')),
                ('description_en', models.CharField(max_length=500, verbose_name='Описание на [English]')),
                ('description_list_en', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание на [English]')),
                ('title_uz', models.CharField(max_length=60, verbose_name='Название на [Uzbek]')),
                ('description_uz', models.CharField(max_length=500, verbose_name='Описание на [Uzbek]')),
                ('description_list_uz', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Описание на [Uzbek]')),
                ('limit_sessions', models.PositiveSmallIntegerField(default=3, verbose_name='Лимит сессий')),
                ('price', models.PositiveIntegerField(verbose_name='Цена подписки в месяц в тийинах')),
                ('ordering', models.PositiveSmallIntegerField(default=10, verbose_name='Позиция в списке')),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='Сумма в тийинах')),
                ('additional_parameters', models.JSONField(blank=True, default=dict, null=True, verbose_name='Дополнительные параметры')),
                ('payment_service', models.CharField(blank=True, choices=[('splay', 'Splay'), ('octo', 'Octo')], max_length=10, null=True, verbose_name='Платежная служба')),
                ('transaction_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='Provider transction ID')),
                ('performed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('username', models.CharField(max_length=60, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='IntermediateSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_debiting', models.DateField(blank=True, null=True, verbose_name='Дата следующего списания')),
                ('auto_payment', models.BooleanField(default=True)),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='payment.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payment.account')),
            ],
            options={
                'verbose_name': 'Промежуточная модель подписок',
                'verbose_name_plural': 'Промежуточная модель подписок',
            },
        ),
        migrations.AddConstraint(
            model_name='intermediatesubscription',
            constraint=models.UniqueConstraint(fields=('subscription_type', 'user'), name='Unique Subscription Type'),
        ),
    ]
