# Generated by Django 4.2.8 on 2023-12-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_active',
        ),
        migrations.AddField(
            model_name='card',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирована'),
        ),
    ]
