# Generated by Django 4.2.8 on 2023-12-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-create_time'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='subscription_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID Подписки'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='additional_parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительные параметры'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_service',
            field=models.CharField(blank=True, choices=[('splay', 'Splay'), ('payme', 'Payme'), ('payme-card', 'Payme Card'), ('click', 'Click'), ('apelsin', 'Apelsin'), ('paynet', 'Paynet'), ('octo', 'Octo'), ('payze', 'Payze')], max_length=10, null=True, verbose_name='Платежная служба'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='payment_tra_transac_143f1c_idx'),
        ),
    ]
