# Generated by Django 4.2.8 on 2023-12-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_card_is_active_card_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expiration',
            field=models.CharField(max_length=16, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=32, null=True, verbose_name='Номер'),
        ),
    ]
