# Generated by Django 4.2.8 on 2023-12-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_options_receipt_subscription_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='info',
        ),
    ]
