# Generated by Django 4.2.8 on 2024-01-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_receipt_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_service',
            field=models.CharField(blank=True, choices=[('splay', 'Splay'), ('payme', 'Payme'), ('payme-card', 'Payme Card'), ('payze-card', 'Payze Card'), ('click', 'Click'), ('apelsin', 'Apelsin'), ('paynet', 'Paynet'), ('octo', 'Octo'), ('payze', 'Payze')], max_length=10, null=True, verbose_name='Платежная служба'),
        ),
    ]
