# Generated by Django 4.2.8 on 2023-12-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_card_expiration_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='expiration',
        ),
        migrations.AddField(
            model_name='card',
            name='expire',
            field=models.CharField(max_length=16, null=True, verbose_name='Срок истечения'),
        ),
    ]
