# Generated by Django 4.2.8 on 2023-12-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_card_expiration_card_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='auto_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен автоматический'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='info',
            field=models.CharField(max_length=128, verbose_name='Информация'),
        ),
    ]
